name: CI - ClassFamilyTree Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ClassFamilyTree.Tests/ClassFamilyTree.Tests.csproj

    - name: Build solution
      run: dotnet build ClassFamilyTree.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ClassFamilyTree.Tests/ClassFamilyTree.Tests.csproj --no-build --verbosity normal
