name: Build și Testare .NET Framework

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout cod
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore ClassFamilyTree/ClassFamilyTree.sln

    - name: Build solution
      run: msbuild ClassFamilyTree/ClassFamilyTree.sln /p:Configuration=Release

    - name: Find vstest.console.exe path
      id: find-vstest
      shell: powershell
      run: |
        $vstest = Get-ChildItem -Path "C:\Program Files\Microsoft Visual Studio\" -Recurse -Filter vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
        echo "VSTEST_CONSOLE=$vstest" >> $env:GITHUB_ENV

    - name: Run unit tests
      run: |
        "$env:VSTEST_CONSOLE" "ClassFamilyTree/ClassFamilyTree.Tests/bin/Release/net8.0/ClassFamilyTree.Tests.dll"
      shell: powershell

    - name: Create deployment folder
      run: mkdir deploy

    - name: List files after build
      shell: powershell
      run: Get-ChildItem -Recurse

    - name: Deploy ClassFamilyTree output
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path deploy
        Copy-Item -Path ClassFamilyTree/ClassFamilyTree/bin/Release/net8.0/* -Destination deploy -Recurse -Force
