name: CI - Classic .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild ClassFamilyTree.sln /p:Configuration=Release

    - name: Run tests with VSTest.Console
      run: |
        dir /s /b *.Tests.dll
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" ClassFamilyTree.Tests\bin\Release\ClassFamilyTree.Tests.dll
